### ISSUE TITLE
NuGet installation broken since 1.2.23

### ISSUE THREAD

**Issue by vitaly-t** [johnpapa/Angular-NuGet#2]
I have been using all of the AngularJS updates via NuGet, and starting with version 1.2.23 it all stopped working. First I noticed it under VS 2010 where I have the latest version of NuGet, and even when using the command line directly, the effect is the same: all AngularJS packages are downloaded empty.

If I issue the following command, I get everything correctly:
NuGet.exe install AngularJS.Core -version 1.2.22

But if I issue the following commands, or ones with higher version, it doesn't work:
1. NuGet.exe install AngularJS.Core -version 1.2.23
2. NuGet.exe install AngularJS.Core

The last commands download only the right NUPKG file, but no content with them, i.e. folder  content\scripts with all the scripts doesn't download for any version after 1.2.22

The same goes for AngularJS 1.3 packages since recent updates.

I'm using the latest NuGet.exe from the official website.

**Comment by KthProg** [comment]
I'm having this issue for .NET Core web project in VS 2017. The NuGet package does nothing except add to the list of dependencies.

**Comment by renatfx** [comment]
This is due to NuGet v3. It does not accept Content inside packages anymore. NuGet now is only about .NET code, portable (cross platform), fast  to download & cached, user- or even machine-wide, with new MSBuild 15 in mind (support targets/tasks), but only .NET. It is still backward compatible with old-style MSBuild and as a result old (pre VS 15 which is VS2017) project format. So you can use these AngularJS v1 packages with either previous versions of VS, or old project templates (non-netcore; e.g. classical ASP.NET MVC 5) in VS2017. To use any version of AngularJS packages in the new type of VS projects (MSBuild 15+), you'd better consume NPM (recommended) or Bower.

**Comment by KthProg** [comment]
Well that's stupid but thanks lol I downloaded it through npm instead.
